name: Automated dependency update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update dependencies
      run: |
        npm install
        npm audit fix --force
        npm update
        npm run build && npm run package
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Automated dependency updates"
        commit-message: "Automated dependency updates"
        body: "Created by running npm audit fix --force and npm update"
        author: "Florian Wilhelm <fwilhelm.wgt+github@gmail.com>"
        token: ${{ secrets.PAT }}
